default_shape_identifier: "default"

prefixes:
    ":":        "http://example.org/"
    "dc:":      "http://purl.org/dc/elements/1.1/"
    "dcterms:": "http://purl.org/dc/terms/"
    "dct:":     "http://purl.org/dc/terms/"
    "foaf:":    "http://xmlns.com/foaf/0.1/"
    "owl:":     "http://www.w3.org/2002/07/owl#"
    "rdf:":     "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    "rdfs:":    "http://www.w3.org/2000/01/rdf-schema#"
    "schema:":  "http://schema.org/"
    "skos:":    "http://www.w3.org/2004/02/skos/core#"
    "skosxl:":  "http://www.w3.org/2008/05/skos-xl#"
    "wdt:":     "http://www.wikidata.org/prop/direct/"
    "xsd:":     "http://www.w3.org/2001/XMLSchema#"

extra_shape_elements:
- "closed"

extra_statement_template_elements:
- "min"
- "max"

picklist_elements:
- "propertyID"
- "valueNodeType"
- "valueDataType"

list_item_separator: ","

extra_value_node_types:
- "uri"
- "nonliteral"

extra_element_aliases:
    "PropID": "propertyID"
    "PropLabel": "propertyLabel"
    "Value": "valueConstraint"
    "ValueType": "valueConstraintType"
    "DataType": "valueDataType"
    "NodeType": "valueNodeType"
    "ShapeRef": "valueShape"
    "Mand": "mandatory"
    "Rep": "repeatable"
